# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      unzip terraform_0.15.5_linux_amd64.zip
      sudo mv terraform /usr/bin/terraform
      sudo chmod 755 /usr/bin/terraform
      rm terraform_0.15.5_linux_amd64.zip
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
