tasks:
  - init: |
      wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      unzip terraform_0.15.5_linux_amd64.zip
      sudo mv terraform /usr/bin/terraform
      sudo chmod 755 /usr/bin/terraform
      rm terraform_0.15.5_linux_amd64.zip
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      terraform init