name: Main
on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Main
    steps:
    - uses: actions/checkout@v2
    - uses: terraform-linters/setup-tflint@v1
    - name: Tflint
      run: tflint -f compact ./terraform
