name: Main
on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'
  pull_request:
    branches: [ master ]
jobs:
  lint:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    name: lint
    steps:
    - uses: actions/checkout@v2
    - uses: terraform-linters/setup-tflint@v1
    - name: Tflint
      run: tflint -f compact ./terraform   
  provision:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    name: provision
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token:  ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Format
      id: fmt
      working-directory: ./terraform
      run: terraform fmt -check
    - name: Terraform Init
      id: init
      working-directory: ./terraform
      run: terraform init
    - name: Terraform Validate
      id: validate
      working-directory: ./terraform
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      working-directory: ./terraform
      run: terraform plan -no-color
  build:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    #needs: [provision, build]
    steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.0
      with:
        app-name: function-app-e3bf2njz1skn2aeqr0av
