name: Main
on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Main
    steps:
    - uses: actions/checkout@v2
    - uses: terraform-linters/setup-tflint@v1
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token:  ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Format
      id: fmt
      working-directory: ./terraform
      run: terraform fmt -check
    - name: Terraform Init
      id: init
      working-directory: ./terraform
      run: terraform init
    - name: Terraform Validate
      id: validate
      working-directory: ./terraform
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      working-directory: ./terraform
      run: terraform plan -no-color


#    - uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: '3.1.x'
##    - name: Azure Functions Action
##      uses: Azure/functions-action@v1.4.0
##      with:
##        app-name: jonny
       
        
#    - name: Tflint
#      run: tflint -f compact ./terraform
#    - name: terraform
#      run: cd ./terraform && terraform plan
#    - name: az
#      run: az --version
##    - name: func
##      run: func --version
#    - name: dotnet
#      run: dotnet --list-sdks
      

