name: Main
on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/**'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Main
    steps:
    - uses: actions/checkout@v2
    - uses: terraform-linters/setup-tflint@v1
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token:  ${{ secrets.TERRAFORM_IO_TOKEN }}
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
##    - name: Azure Functions Action
##      uses: Azure/functions-action@v1.4.0
##      with:
##        app-name: jonny
       
        
#    - name: Tflint
#      run: tflint -f compact ./terraform
    - name: terraform
      run: cd ./terraform && terraform plan
#    - name: az
#      run: az --version
##    - name: func
##      run: func --version
#    - name: dotnet
#      run: dotnet --list-sdks
      

